project:
  type: website

website:
  title: "My Cloudy Future"
  navbar:
    right:
      - about.qmd
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/danielle-b
      - icon: linkedin
        href: https://linkedin.com/in/daniellebrantley
      - icon: twitter
        href: https://twitter.com/danianceb

format:
  html:
    theme: litera
    css: styles.css
    
    
execute:
  freeze: auto



