project:
  type: website

website:
  title: "My Cloudy Future"
  navbar:
    right:
      - projects.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/danielle-b
      - icon: linkedin
        href: https://linkedin.com/in/daniellebrantley
      - icon: twitter
        href: https://twitter.com/danianceb
  page-footer: 
    center: "Copyright 2024, My Cloudy Future" 

format:
  html:
    theme: lumen
    css: styles.css
    
    
execute:
  freeze: auto



