---
title: "30 Day Cloud Challenge: Day 30"
author: "Danielle Brantley"
date: "2024-03-30"
categories: [aws]
---

Wow! That went by quick!

I cannot believe that I am at the end of the 30 Day Cloud Challenge! It seems like it was just yesterday that I learned about the Cozy Cloud Crew Discord channel and the 30 Day Cloud Challenge.

I am in awe of what I learned and how much I learned! I feel much more comfortable with AWS than I did 30 days ago.

This challenge has inspired me to want to do the following:

-   Learn more about the services provided by AWS

    -   I want to learn more about the services that I interacted with during this challenge, particularly EC2, IAM, Amazon VPC, and AWS VPN.

    -   I'm interested in exploring other AWS services such as Lambda, CloudWatch, and Elastic Beanstalk. I'm especially interested in their Container services.

-   Begin learning about other areas in tech

    -   During this challenge, I became very interested in learning more about networking and security. I created an account on TryHackMe and I will use this resource to learn a bit more about these topics. I believe that fully grasping the concepts of networking and cyber security even if it's just basic knowledge will make me a better engineer.

-   Change how I learn technical topics

    -   Learning a new technical tool or concept can be a bit overwhelming. This 30 day challenge has inspired me to try learning different technical topics using a similar day by day approach. I have learned that spending just an hour or two a day and being consistent can take me further than I imagined. This leads me to my next point.

-   What other topics can I learn using the 30 Day approach?

    -   Well, inspired by this [Made by GPS](https://www.youtube.com/watch?v=ZwUc07UsI-c&t=611s){target="_blank"} video(really her entire YouTube channel), I decided to read the first 10 chapters of Linux Basics for Hackers by Occupy the Web. I already started Chapter 1 and I'm in the middle of writing a blog post detailing my notes.

    -   I am currently learning programming and this challenge has helped me alter how I study.

    -   I decided I wanted to sit for AWS Solutions Architect certification this year and I'm going to use this approach to complete a Solutions Architect course I brought earlier this year.

    -   Later this year, I want to the 30 Day Cloud Beginner Challenge again using Azure.

All in all, this 30 Day Cloud Challenge was an amazing learning experience! This was a fun way for me to get more hands on with AWS. AWS does not seem as overwhelming anymore! I am so happy to have come across the Cozy Cloud Crew and learn from everyone in the community. I'm looking forward to continuous learning and growing with this community. I eventually want a job opportunity where I am able to put these skills to use.
