---
title: "30 Day Cloud Challenge: Days 7-8"
author: "Danielle Brantley"
date: "2024-03-07"
categories: [news, cloud]
---

For Days 7-8 of the challenge, I was given the following prompt: 

*Learn about the AWS Well Architected Framework and an overview of what an S3 bucket is. Why do we use one? What can we store in there?*

I'll start off with explaining the AWS Well Architected Framework. 

Solid architecture is a key foundation for building a successful business. The **AWS Well Architected Framework** helps users understand the pros and cons of decisions made while building cloud architectures and systems on the AWS platform. The framework is a guide to creating top-notch cloud architectures on AWS. Consisting of six pillars, it ensures security, reliability, efficiency, affordability, and sustainability for your workloads.

[AWS documentation](https://docs.aws.amazon.com/wellarchitected/latest/framework/definitions.html){target="_blank"} defines the pillars as the following:

1. Operational Excellence
2. Security
3. Reliability
4. Performance Efficiency
5. Cost Optimization
6. Sustainability

Let me break this down further.

* **Operational Excellence**
  + The operational excellence pillar includes the ability to ensure smooth development and execution of workloads, provide insights into their performance, and foster continuous improvement for better business results. Some of its designs principles include performing operations as code, making frequent, small, reversible changes and anticipating failure.


* **Security**
  + The security pillar explains how cloud services can help you secure your information, programs, and important files, making your entire system more secure. Its design principles include implementing a strong identity foundation, applying security at every layer and automating security best practices.


* **Reliability**
  + In essence, the reliability pillar ensures a workload consistently performs its intended function as expected throughout its lifecycle. This encompasses both operating and testing the workload effectively. Design principles for this pillar include scaling horizontally to increase workload availability, implementing test recovery procedures and managing change in automation.


* **Performance Efficiency**
  + Performance efficiency is about optimizing how you use computing resources to meet current needs, while being flexible to adapt to future demands and advancements. Some of the design principles here include using serverless architectures, going global in minutes and experimenting more often.


* **Cost Optimization**
  + The ability to run systems to deliver business value at the lowest price point. Implementing cloud financial management, adopting a consumption model and measuring overall efficiency are just some of the design principles of this pillar. 


* **Sustainability**
  + The sustainability pillar includes the ability to continuously improve the environmental impact of workloads by minimizing resource usage and maximizing efficiency. A few of the design principles here are establishing sustainability goals, maximizing utilization and using managed services. 
  
All in all, the framework provides a way to measure your architectures against best practices and make improvements as needed. 
  
Now let's get into the second part of the prompt. What is S3?

[**Amazon S3 (Simple Storage Service**)](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html){target="_blank"} is an object storage service that offers scalability, data availability, performance and security. This service is designed for storing and retrieving any amount of data at any time, from anywhere on the internet. It stores data as objects within buckets. A object is a file and any metadata that describes the file. A bucket is a container for objects. All types of files can be stored in S3 such as text files, videos, and even entire databases. Some of the use cases of S3 include websites, IoT devices, and data analytics. 

As I mentioned in a previous post, I have experience using Amazon S3. At a previous company our social media analytics vendor would house our data in an S3 bucket. From there, I would create a table in Big Query to store our data and use Google's data transfers service to transfer our data into the newly created Big Query table. I even tried hosting a static website in S3! 

In the next few days, I will spend more time becoming familiar with S3 and its capabilities. 






